<div class="row">
        <div class="span12">
            <h2><?php echo $this->translate('Privacy') ?></h2>
            <p>In neque urna, egestas vitae hendrerit et, pretium eget sapien. Quisque ut pellentesque purus. Proin facilisis diam vitae libero faucibus porta. Fusce quis sagittis magna. Fusce consequat molestie dictum. Aliquam sit amet nibh eu lorem placerat accumsan sit amet at nibh. Nullam condimentum sem id sem pharetra a mattis massa sollicitudin. Mauris vehicula erat ut est posuere tincidunt. Aenean consequat sapien vel sapien porttitor malesuada. Vivamus nec sollicitudin est. Ut justo purus, lacinia vel ullamcorper a, ornare a magna.</p>
        </div>
    </div>
